# Kelas Pemrograman Desktop B
# Tema = Laundry
# Anggota Kelompok :
# 230411100045 - Dani Subianto
# 230411100163 - Hengki Dwi Kurniawan
# 230411100017 - Wiwik Ainun Janah
# 230411100186 - Yasmin Azzahra
# 230411100001 - Intan Aulia Majid

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(683, 585)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 631, 511))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_4 = QtWidgets.QLabel(parent=self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Swis721 Hv BT")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(parent=self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 291, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 40, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 250, 131, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 251, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 120, 251, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 190, 251, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.radioButton = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 280, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 310, 111, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 70, 281, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(110, 90, 41, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(150, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.spinBox = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(20, 50, 121, 22))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.spinBox_2.setGeometry(QtCore.QRect(150, 50, 111, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 110, 151, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.spinBox_5 = QtWidgets.QSpinBox(parent=self.groupBox_2)
        self.spinBox_5.setGeometry(QtCore.QRect(20, 110, 81, 22))
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 49, 16))
        self.label_6.setObjectName("label_6")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(330, 230, 281, 191))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_10.setObjectName("label_10")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.groupBox_3)
        self.dateEdit.setGeometry(QtCore.QRect(10, 40, 121, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(150, 20, 101, 16))
        self.label_12.setObjectName("label_12")
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=self.groupBox_3)
        self.dateEdit_2.setGeometry(QtCore.QRect(149, 40, 121, 22))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(90, 90, 181, 24))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 120, 191, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 120, 61, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 90, 71, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_12.setText("0")
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(120, 150, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_36 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_36.setGeometry(QtCore.QRect(10, 150, 111, 16))
        self.label_36.setObjectName("label_36")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 440, 591, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_41 = QtWidgets.QLabel(parent=self.tab)
        self.label_41.setGeometry(QtCore.QRect(340, 420, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_13 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 50, 281, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(320, 50, 281, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 90, 581, 391))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(11)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_14 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.tab_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 50, 281, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.tab_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(320, 50, 281, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(20, 90, 581, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(40, 60, 49, 16))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(30, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.tab_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 60, 561, 372))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(15, 15, 15, 15)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_20 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_24.setObjectName("label_24")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_27.setObjectName("label_27")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_29)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_9)
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_10)
        self.dateEdit_3 = QtWidgets.QDateEdit(parent=self.formLayoutWidget)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateEdit_3)
        self.dateEdit_4 = QtWidgets.QDateEdit(parent=self.formLayoutWidget)
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateEdit_4)
        self.spinBox_3 = QtWidgets.QSpinBox(parent=self.formLayoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox_3)
        self.spinBox_4 = QtWidgets.QSpinBox(parent=self.formLayoutWidget)
        self.spinBox_4.setObjectName("spinBox_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox_4)
        self.spinBox_6 = QtWidgets.QSpinBox(parent=self.formLayoutWidget)
        self.spinBox_6.setObjectName("spinBox_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spinBox_6)
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_11)
        self.label_40 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_40.setObjectName("label_40")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_40)
        self.lineEdit_20 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_20)
        self.lineEdit_21 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_21)
        self.lineEdit_22 = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_22)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 440, 131, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButton_4.setGeometry(QtCore.QRect(170, 440, 131, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(460, 440, 131, 24))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_18 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(30, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=self.tab_5)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 60, 571, 291))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(15, 10, 15, 10)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_30 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_31)
        self.label_32 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_32)
        self.label_33 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_33)
        self.label_34 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_34.setObjectName("label_34")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_34)
        self.lineEdit_13 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_15)
        self.textEdit = QtWidgets.QTextEdit(parent=self.formLayoutWidget_2)
        self.textEdit.setObjectName("textEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit)
        self.lineEdit_16 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_16)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.tab_5)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 360, 131, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.tab_5)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 360, 131, 24))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.tab_5)
        self.pushButton_8.setGeometry(QtCore.QRect(470, 360, 131, 24))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_19 = QtWidgets.QLabel(parent=self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(30, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayoutWidget_3 = QtWidgets.QWidget(parent=self.tab_6)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(30, 60, 561, 311))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(15, 10, 15, 10)
        self.formLayout_3.setSpacing(10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_35 = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        self.label_35.setObjectName("label_35")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_35)
        self.label_37 = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        self.label_37.setObjectName("label_37")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_37)
        self.label_38 = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        self.label_38.setObjectName("label_38")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_38)
        self.label_39 = QtWidgets.QLabel(parent=self.formLayoutWidget_3)
        self.label_39.setObjectName("label_39")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_39)
        self.lineEdit_17 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_3)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_17)
        self.lineEdit_18 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_3)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_18)
        self.lineEdit_19 = QtWidgets.QLineEdit(parent=self.formLayoutWidget_3)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_19)
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.formLayoutWidget_3)
        self.textEdit_2.setObjectName("textEdit_2")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.textEdit_2)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 380, 131, 24))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.tab_6)
        self.pushButton_10.setGeometry(QtCore.QRect(170, 380, 131, 24))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.tab_6)
        self.pushButton_11.setGeometry(QtCore.QRect(460, 380, 131, 24))
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "TAMBAH DATA"))
        self.groupBox.setTitle(_translate("MainWindow", "Pelanggan"))
        self.label.setText(_translate("MainWindow", "Nama :"))
        self.label_2.setText(_translate("MainWindow", "Telepon :"))
        self.label_3.setText(_translate("MainWindow", "Alamat"))
        self.label_5.setText(_translate("MainWindow", "Jenis Kelamin"))
        self.radioButton.setText(_translate("MainWindow", "Laki - Laki"))
        self.radioButton_2.setText(_translate("MainWindow", "Perempuan"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Cucian"))
        self.label_7.setText(_translate("MainWindow", "Jml Baju : "))
        self.label_8.setText(_translate("MainWindow", "Paket :"))
        self.label_9.setText(_translate("MainWindow", "Jml Celana :"))
        self.label_6.setText(_translate("MainWindow", "Berat/kg"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Transaksi"))
        self.label_10.setText(_translate("MainWindow", "Tanggal Transaksi"))
        self.label_11.setText(_translate("MainWindow", "Diskon%"))
        self.label_12.setText(_translate("MainWindow", "Tanggal Selesai"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))
        self.label_15.setText(_translate("MainWindow", "Total Harga "))
        self.comboBox.setItemText(0, _translate("MainWindow", "Lunas"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Belum Lunas"))
        self.label_36.setText(_translate("MainWindow", "Status Pembayaran"))
        self.pushButton_2.setText(_translate("MainWindow", "Simpan"))
        self.label_41.setText(_translate("MainWindow", "NB : \"Silahkan Klik Apply untuk mendapatkan total harga\""))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Transaksi"))
        self.label_13.setText(_translate("MainWindow", "Data Transaksi"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Pelanggan..."))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Status"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID TRANSAKSI"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PELANGGAN"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TGL TRANSAKSI"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TGL SELESAI"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "BERAT/KG"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "JML BAJU"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "JML CELANA"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "PAKET"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "TOTAL HARGA"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "STATUS"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "DISKON"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data Transaksi"))
        self.label_14.setText(_translate("MainWindow", "Data Pelanggan"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "Nama..."))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Alamat..."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID PELANGGAN"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAMA"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TELEPON"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "JENIS KELAMIN"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ALAMAT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Data Pelanggan"))
        self.label_16.setText(_translate("MainWindow", "Transaksi"))
        self.label_20.setText(_translate("MainWindow", "Id_Transaksi"))
        self.label_21.setText(_translate("MainWindow", "Pelanggan"))
        self.label_22.setText(_translate("MainWindow", "Tgl Transaksi"))
        self.label_23.setText(_translate("MainWindow", "Tgl Selesai"))
        self.label_24.setText(_translate("MainWindow", "Jml Baju"))
        self.label_25.setText(_translate("MainWindow", "Jml Celana"))
        self.label_26.setText(_translate("MainWindow", "Berat/Kg"))
        self.label_27.setText(_translate("MainWindow", "Paket"))
        self.label_28.setText(_translate("MainWindow", "Status"))
        self.label_29.setText(_translate("MainWindow", "Diskon"))
        self.label_40.setText(_translate("MainWindow", "Total Harga"))
        self.pushButton_3.setText(_translate("MainWindow", "Previous"))
        self.pushButton_4.setText(_translate("MainWindow", "Next"))
        self.pushButton_5.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Record Transaksi"))
        self.label_18.setText(_translate("MainWindow", "Pelanggan"))
        self.label_30.setText(_translate("MainWindow", "Id Pelanggan"))
        self.label_31.setText(_translate("MainWindow", "Nama"))
        self.label_32.setText(_translate("MainWindow", "Telepon"))
        self.label_33.setText(_translate("MainWindow", "Jenis Kelamin"))
        self.label_34.setText(_translate("MainWindow", "Alamat"))
        self.pushButton_6.setText(_translate("MainWindow", "Previous"))
        self.pushButton_7.setText(_translate("MainWindow", "Next"))
        self.pushButton_8.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Record Pelanggan"))
        self.label_19.setText(_translate("MainWindow", "Paket"))
        self.label_35.setText(_translate("MainWindow", "Id Paket"))
        self.label_37.setText(_translate("MainWindow", "Nama Paket"))
        self.label_38.setText(_translate("MainWindow", "Harga/kg"))
        self.label_39.setText(_translate("MainWindow", "Deskripsi"))
        self.pushButton_9.setText(_translate("MainWindow", "Previous"))
        self.pushButton_10.setText(_translate("MainWindow", "Next"))
        self.pushButton_11.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Record Paket"))
